services:
  avalanche:
    image: quay.io/prometheuscommunity/avalanche
    command:
      - --gauge-metric-count=5
      - --label-count=3
      - --series-count=10
      - --value-interval=15
      - --series-interval=120
      - --metric-interval=600
      - --port=9001
    ports:
      - "9001:9001"

  prometheus:
    image: prom/prometheus:v3.10.0
    volumes:
      - ./dev/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - avalanche

  victoriametrics:
    image: victoriametrics/victoria-metrics
    command:
      - -promscrape.config=/etc/victoriametrics/scrape.yml
    volumes:
      - ./dev/victoriametrics-scrape.yml:/etc/victoriametrics/scrape.yml:ro
    ports:
      - "8428:8428"
    depends_on:
      - avalanche

  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./dev/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
